### ISSUE TITLE
No dice

### ISSUE THREAD

**Issue by AndyObtiva** [grodowski/undercover-ci#203]
Hi, I tried undercover-ci and it didn't work. I deleted tests from one OSS repo (https://github.com/AndyObtiva/easily_typable) in master, which dropped its coverage from 77% to 38% (as you can see on its project page), but undercover-ci still doesn't give me any warnings about it whether I check it on the website or run it via the command line "undercover -c HEAD~1"

The undercover-ci dashboard says the commit is still in_progress (18 minutes passed). 
https://drive.google.com/file/d/1UoN4RYjKHJ93uJ1I0sC6vtBy80Tx2rEW/view?usp=sharing

**Comment by grodowski** [comment]
Hi @AndyObtiva! Thanks for reporting this issue and please understand that the service still has some rough edges. But, good news is that you're *very close* to a successful setup. Here's what I found:

- your coverage upload from travis is set up correctly
- the most recent analysis of [`f7bea666`](https://github.com/AndyObtiva/easily_typable/commit/f7bea6668790f05471c7cda611ab285d6609b436) failed, most probably because of a known bug related to force pushing -  the [GitHub-reported `before` SHA is incorrect](https://github.com/grodowski/undercover-ci/blob/71064a16075c19f8e486c0857a1c319c80198102/app/models/data_objects/check_run_info.rb#L53-L54) ([`ea53d4f9`](https://github.com/AndyObtiva/easily_typable/commit/ea53d4f9) in this case) and needs to be fixed. The job failed with an exception and I'll do my best to ship a fix soon. I also need to add cleanup logic for checks that never received coverage data or failed with a new `expired` state.

What I can recommend to you to properly try out the service is to push a new commit that makes a change to an untested code path (removing just the specs won't trigger any undercover warnings).

**Comment by AndyObtiva** [comment]
OK, I just pushed another commit (no force push) that clearly added extra gibrish implementation code with no test-coverage. Fortunately, the local undercover command detected the lack of coverage introduced: 

```
undercover: 👮‍♂️ some methods have no test coverage! Please add specs for methods listed below
🚨 1) node `__methodize__` type: class method,
      loc: lib/easily_typable.rb:57:74, coverage: 0.0%
57:   def self.__methodize__(text) hits: n/a
58:     if true hits: 0
59:       puts 'true' hits: 0
60:     elsif false hits: 0
61:       puts 'false' hits: 0
62:     elsif true hits: 0
63:       puts 'true' hits: 0
64:     elsif false hits: 0
65:       puts 'false' hits: 0
66:     elsif true hits: 0
67:       puts 'true' hits: 0
68:     elsif false hits: 0
69:       puts 'false' hits: 0
70:     end hits: n/a
71:     text.split(/::/).last.gsub(/([A-Z]+)([A-Z])/,'\1_\2'). hits: n/a
72:     gsub(/([a-z])([A-Z])/,'\1_\2'). hits: n/a
73:     downcase hits: 0
74:   end hits: n/a
Undercover finished in 0.0261s
```

The online dashboard on the other hand says "in_progress (15 minutes ago)" and seems stuck just like before.

Either way, at least I got to see undercover-CI in action locally. It's exactly what I was looking for. Hopefully, it would also support my other use-case from my previous message in the future (e.g. deleting/fudging tests causing a warning)

Thank you. I understand this project is still a very early release. I look forward to future updates.

**Comment by AndyObtiva** [comment]
Nevermind, I got Undercover-CI working on another project ([Glimmer](https://github.com/AndyObtiva/glimmer)):

https://undercover-ci.com/checks/4849

```
warning lib/glimmer/dsl/engine.rb:112:150
Block block (args, block). Coverage: 87.5% (contains untested diff lines).
warning lib/glimmer/dsl/engine.rb:162:179
Instance method interpret. Coverage: 66.67% (contains untested diff lines).
```

It is not exactly true since the lines mentioned get tested via meta-programming, but this is besides the point. Everyone knows computers can be precise but not accurate sometimes. :)

Thanks and cheers. I am closing this issue for now. I look forward to future developments in Undercover-CI in the meantime.
